// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a24ef678-43d8-4cd1-9aed-4bfb3b4ac8b7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onD3SwitchChange();
void onD4SwitchChange();
void onLedSwitchChange();

bool d3_switch;
bool d4_switch;
bool led_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(d3_switch, READWRITE, ON_CHANGE, onD3SwitchChange);
  ArduinoCloud.addProperty(d4_switch, READWRITE, ON_CHANGE, onD4SwitchChange);
  ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
